# Consepts:

####   Introduction to tensors
####   Creating tensors
####   Getting information from tensors
####   Manipulating tensors
####   Dealing with tensor shapes
####   Indexing on tensors
####   Mixing PyTorch tensors and NumPy
####   Reproducibility
####   Running tensors on GPU  

### Importing PyTorch


In [1]:
import torch 
print (torch.__version__)

1.12.1+cu113


In [2]:
! nvidia-smi

Mon Dec  5 23:49:46 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P0    28W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

###  Introduction to Tensor 


In [3]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
# we can check the dimensions of a tensor using ndam
print (scalar.ndim)

tensor(7)
0


In [4]:
# retrieving the number from the tensor
scalar.item()  #only works with one-element tensors

7

In [5]:
# A vector is a single dimension tensor but can contain many numbers.
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)

tensor([7, 7])
1


In [6]:
# Check shape of vector
vector.shape

torch.Size([2])

In [7]:
# matrix, a set of numbers arranged in rows and columns

matrix = torch.tensor([[7, 8], 
                       [9, 10]])
print(matrix)
print(matrix.ndim)
print (matrix.shape)
#print(matrix.size())

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [8]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 3, 3])


### Random tensors

In [9]:
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)


tensor([[0.4969, 0.9305, 0.9172, 0.7672],
        [0.4393, 0.4712, 0.0407, 0.4733],
        [0.8335, 0.7477, 0.7032, 0.3831]])


In [10]:
print(random_tensor.dtype)
print(random_tensor.ndim)

torch.float32
2


### Zeros and ones

In [11]:
zeros = torch.zeros(size=(3, 4))
print(zeros)
zeros.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


torch.float32

In [12]:
ones = torch.ones(size=(3, 4))
print(ones)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Creating a range

In [13]:
# using torch.arange(start, end, step)
x = torch.range(0 , 20 , 2)
x

<ipython-input-13-db7250a4e510>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x = torch.range(0 , 20 , 2)


tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [14]:
y = torch.arange(0 , 20 , 2)
y

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
zeros = torch.zeros_like(x)
zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Manipulating tensors (tensor operations)

In [16]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)

tensor([11, 12, 13])


In [17]:
tensor * 10 

tensor([10, 20, 30])

In [18]:
tensor - 10 

tensor([-9, -8, -7])

In [19]:
# Element-wise matrix multiplication
tensor * tensor 

tensor([1, 4, 9])

In [20]:
# Matrix multiplication --> dot prod.
print (tensor @ tensor )
print(torch.matmul(tensor, tensor))

tensor(14)
tensor(14)


In [21]:
tensor_A = torch.tensor([[1., 2.],
                   [3., 4.],
                   [5., 6.]])


In [22]:
tensor_B = tensor_A
tensor_B

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


### Finding the min, max, mean, sum

In [23]:
tensor = torch.arange(0, 100, 3)

In [24]:
print ("tensor min"+ str(tensor.min()))
print ("tensor max"+ str(tensor.max()))
print ("tensor mean"+str(tensor.type(torch.float32).mean()))
print ("tensor sum"+str(tensor.sum()))



tensor mintensor(0)
tensor maxtensor(99)
tensor meantensor(49.5000)
tensor sumtensor(1683)


In [25]:
print(tensor.argmin())
print(tensor.argmax())


tensor(0)
tensor(33)


### Reshaping, stacking, squeezing and unsqueezing

In [26]:
x = torch.arange(1, 100 , 10 )
x.reshape(2,5)


tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])

In [27]:
x.view(1, 10)

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [28]:
x = torch.rand(size=(3, 1, 4))
print (x) 
print(x.permute(1,2 , 0))

tensor([[[0.6598, 0.5460, 0.2410, 0.2808]],

        [[0.2423, 0.3486, 0.6381, 0.1282]],

        [[0.3688, 0.3841, 0.7696, 0.8996]]])
tensor([[[0.6598, 0.2423, 0.3688],
         [0.5460, 0.3486, 0.3841],
         [0.2410, 0.6381, 0.7696],
         [0.2808, 0.1282, 0.8996]]])


### PyTorch tensors & NumPy

In [29]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

### Getting PyTorch to run on the GPU

In [30]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [31]:


# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device



     


'cuda'

In [32]:
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

In [33]:
# Putting a tensor on GPU using to(device)  returns a copy of that tensor
tensor = torch.tensor([1, 2, 3])

# Tensor on CPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor = tensor.to(device)
tensor

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')